LAZY_PLUGIN_SPEC = {}
-- This queues something for us
function spec(item) table.insert(LAZY_PLUGIN_SPEC, { import = item }) end

-- TODO test the todo comment

-- disable netrw for nvim-tree instead
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

require("user.options")

-- autogenerated help
spec("user.legendary")

spec("user.color_scheme")
spec("user.telescope")
spec("user.nvim_tree")

require("user.line_numbers")

spec("user.editor")

spec("user.git.diffview")
spec("user.git.linker")
spec("user.git.blame")
spec("user.git.signs")

spec("user.markdown.glow")
spec("user.markdown.peek")

spec("user.lsp.treesitter")
spec("user.lsp.cmp")
spec("user.lsp.mason")
spec("user.lsp.setup")
spec("user.lsp.lang.json")
spec("user.lsp.outline")
spec("user.lsp.none_ls")

spec("user.which_key")

spec("user.ui.lualine")
spec("user.ui.incline")
spec("user.ui.bufferline")

spec("user.windows.windows")
spec("user.windows.winshift")

spec("user.wakatime")

require("user.meta.show_messages")

-- This loads last
require("user.lazy")
